### ISSUE TITLE
[MODAL] Detalle arriba de mapa

### ISSUE THREAD

**Issue by dadatina** [chicasprogramando/coffeemap#18]

**Comment by puribey** [comment]
Hello, bueno, avance bastante pero tengo el siguiente problema: El VisualDetailCafe estaba agarrado de los cafes del mapa. Ahora cuando tocas el cafe del mapa no lo muestra (lo cual esta bien por que tendria que mostrarlo cuando tocas el ver mas). El tema es que estoy teniendo un problema con el handler que hacer que se muestren y creo que tiene que ver con el ButtonGeneral y su evento de click default. Alguno me puede ayudar con esto? Sé que estoy cerca pero no estaría viendo lo que me falta. Probablemente sea algo de vue que no sé como funciona y por eso no puedo encontrarlo 
@alandawi @gianko @ramendezb

**Comment by puribey** [comment]
@alandawi @gianko @ramendezb ya resolvimos el tema con @agottert :)
