### ISSUE TITLE
Fetch Data and Loader Component

### ISSUE THREAD

**Issue by puribey** [chicasprogramando/coffeemap#21]
Mejorar las Actions y Mutations que traen los cafes y los barrios a la aplicación. Hacer una sola action y una sola mutation que lo haga y ponerla en app para que se pueda acceder a esa info desde toda la aplicación. Hacer el componente de Loader con alguna animación y ver de colocarlo o al comienzo, en el VisualIntro o en el mapa cuando este cargando. 
Crear los 3 getters: cafes, cafes con filtros y cafes con barrios

**Comment by alandawi** [comment]
Extra: si se animan y quieren usar **Promise.all**...¡genial!

https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Promise/all
