### ISSUE TITLE
[Componente] visual-slider-item (visual-slide)

### ISSUE THREAD

**Issue by alandawi** [chicasprogramando/coffeemap#8]
![visual-slider-item visual-slide](https://user-images.githubusercontent.com/1291730/34384900-de7c1ac2-eafd-11e7-963f-ca69e5f90086.JPG)

**Comment by agottert** [comment]
@alandawi ya comitie todo, cierro el issue? :)

**Comment by alandawi** [comment]
@agottert ¿ya está todo? ¿Maquetado también?

**Comment by agottert** [comment]
Dada me dijo que lo cierre pero me parece que hay que seguir trabajando algunas cosas por eso te pregunto. Maquetado esta :) ... Aparece en el Storybook

**Comment by alandawi** [comment]
@geraldineinzaghi Cuando tengas un momento ¿Podrás chequear lo que hicieron?
